# Generated by Django 3.2.3 on 2021-05-25 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('estreno', models.DateField(null=True)),
                ('genero', models.CharField(max_length=255)),
                ('idioma', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=7)),
                ('contenido', models.FileField(upload_to='uploads/')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.pelicula')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.persona')),
            ],
        ),
    ]
